services:
  aggregator:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    networks:
      - pubsub-net
    container_name: uts_aggregator

  publisher:
    build: .
    command: ["python", "-m", "src.publisher"]
    profiles:
      - manual
    depends_on:
      - aggregator
    networks:
      - pubsub-net
    environment:
      # Publisher menembak ke container aggregator menggunakan nama service-nya
      - AGGREGATOR_URL=http://aggregator:8080/publish
    container_name: uts_publisher

  test:
    build: .
    command: ["python", "-m", "pytest", "tests/", "-v"]
    profiles:
      - manual
    volumes:
      - ./data:/app/data
    networks:
      - pubsub-net
    container_name: uts_test

networks:
  pubsub-net:
    driver: bridge
